### ISSUE TITLE
Dragon - 1.20 Armor Trims Armor restrictions

### ISSUE THREAD

**Issue by BoredLizard** [OnyxXIII/New-Terrodim-Origins#14]
Would love to see an alteration to the current DB flaw of only being able to wear gold and diamond when armor trims finally get added into the server.

Namely - would love to see the ability become "Can only wear gold and gold trim". Putting a larger emphasis on the already gold loving dragonborn.
- This is a nerf to the early game and midgame because there's now an additional and expensive prerequisite to wearing any armor besides gold.
- This is a buff to the late game, because DB can then wear netherite with gold trim. Whereas before the strongest armor capable of being worn was diamond.
- Overall this is flavor that's mostly inhibitive. But if the addition of netherite's too big an ask, happy to keep the max armor level diamond and go through with the rest of it.

**Comment by OnyxXIII** [comment]
Yep, looks like we can look for that trim:material: nbt

`/give @p minecraft:netherite_helmet{Trim:{**material:"minecraft:gold"**,pattern:"minecraft:vex"}}
`
https://origins.readthedocs.io/en/latest/types/item_condition_types/nbt/

```
"item_condition": {
"type": "origins:nbt",
"nbt": "{Trim:{material:\"minecraft:gold\"}}"
}
```

**Comment by OnyxXIII** [comment]
Done in next update
