### ISSUE TITLE
Rat - Feature Requests

### ISSUE THREAD

**Issue by ShampooAkatsukiFromHonk** [OnyxXIII/New-Terrodim-Origins#16]
Ride dogs: Not only are they the perfect size for a mount, but wharfrats have a special connection with dogs in-lore so having mechanical representation of this would be cool.

Eating bones, ink sacs and leather: I like the idea of being able to eat a few non-food items. It doesn't necessarily have to be limited to the ones I mentioned, but at least those three would be cool.

Scream: A feature I've already proposed. I want to be able to scream using the ability key. If it needs to have a mechanical effect tied to it, then having it highlight phantom and/or players for a couple of seconds would be cool.

Increased knockback: Getting hit doesn't feel impactful enough given how small I am relative to everyone else, so taking extra knockback would be cool. I imagine something to the tune of a x4 knockback multiplier.

**Comment by OnyxXIII** [comment]
I humbly add the suggestion:
- much slipperier on ice
- do not sink in deep snow

**Comment by OnyxXIII** [comment]
I also submit: Can ride people

and other animals

basically anything

why not?

**Comment by ShampooAkatsukiFromHonk** [comment]
would it be possible to control the wolf like a horse while riding it?

**Comment by OnyxXIII** [comment]
> would it be possible to control the wolf like a horse while riding it?

Probably not. Mob AI isn't something origins has a framework to meddle with.

> Scream: A feature I've already proposed. I want to be able to scream using the ability key. If it needs to have a mechanical effect tied to it, then having it highlight phantom and/or players for a couple of seconds would be cool.

Done. Technically doesn't need the mechanical effect but it's fun flavor.

**Comment by OnyxXIII** [comment]
> Increased knockback: Getting hit doesn't feel impactful enough given how small I am relative to everyone else, so taking extra knockback would be cool. I imagine something to the tune of a x4 knockback multiplier.

https://origins.readthedocs.io/en/latest/types/power_types/modify_attribute/
https://minecraft.wiki/w/Attribute#:~:text=2048.0-,generic.knockback_resistance,-The%20scale%20of

**Comment by OnyxXIII** [comment]
Everything but the food requests done in next update (largely untested)
