### ISSUE TITLE
Mob Head Equipable for Dragonborn (LOW PRIORITY)

### ISSUE THREAD

**Issue by BoredLizard** [OnyxXIII/New-Terrodim-Origins#19]
Just a minor request to allow Dragonborn to equip mob heads like other races.
As far as I'm aware there's no practical purpose to the heads, it's just fun fashion. So if I'm requesting an actual practical feature for dragonborn feel free to ignore!
If this is more work than it's worth - absolutely don't mess with it, but if it can be input in a couple easy lines I'd appreciate it!

**Comment by OnyxXIII** [comment]
Fixed in next update
