### ISSUE TITLE
Naga Changes *Low Priority*

### ISSUE THREAD

**Issue by GigglingMenace** [OnyxXIII/New-Terrodim-Origins#21]
### Changes to Consumables

It has come to my attention that Naga cannot drink drinkable honey. I would like to make the formal request of being able to do so, along with being able to eat soups and stews, so that I may participate in the Shanty Lantern shindigs whenever Nick gets his setup completed.

He also made a note that fish can eat honey, since fishing with honeycomb is a very efficient fishing tactic, so it doesn't break too far from reality either. Maybe add that I can eat honey comb too? Just food for thought. *heh*

### Naga Song

One day, I was at Austin's base, and sang my passivity song, and Nick was getting the music note effect all the way from his base, but couldn't hear the song. Maybe look into radius effect, so it's not intrusive to other players? But still large enough to help in combat. 

There was also talk with Anna and Austin that maybe I should have different kinds of songs to choose from. Anna suggested a fancy song for social events, and Austin was thinking a song that could summon thunderstorms would be cool, but I think it was mentioned that it could be too OP, since it would make Super Creeper hunting too easy, thus flooding the market with gunpowder. 

### Coral Creation

I remember at some point you mentioned that it didn't make sense for the Naga to uproot a whole coral ocean to make coral homes, which I agree with, since I like the idea of them being underwater sea druids. I'm not entirely sure if that idea was pursued more, but if there was a way to make it happen, that would really improve my quality of life, but also keep from tearing up a very beautiful ocean. If I do get this power, I would want to return it back to its former glory, the coral ocean I'm mining up in the far north east.

Maybe make it limited to where I can only create coral in warm or lukewarm oceans to make it make sense. I think I'm currently living in a lukewarm, since there are still tropical fish, but coral oceans only spawn in warm ocean water, if I remember correctly.

**Comment by OnyxXIII** [comment]
Honey added to naga food list in a recent update.

**Comment by OnyxXIII** [comment]
along with some stews (though maybe not all?)

all origins have always been able to eat suspicious stew

**Comment by OnyxXIII** [comment]
Next update, naga can craft coral blocks from coral not-blocks (which are renewable)

Songs are a big pain and we did decide thunderstorm songs are a bad idea, so I'll solve this out. Come back in a new one if you have more concrete song suggestions, but I'm definitely going to be very harsh vetting those suggestions given their difficulty on average.
