### ISSUE TITLE
Faun - Not Damage (Most) Passive/Neutral Mobs

### ISSUE THREAD

**Issue by HalberdGuard** [OnyxXIII/New-Terrodim-Origins#24]
I'd like to be unable to directly harm non-food, passive or neutral mobs with the exception of Cave Spiders, Spiders, Drowned, Endermen, and Zombified Piglins. (Why are Drowned considered neutral?!)
Also, the completely harmless small slimes, if possible!

Alternatives considered (and tried) in the past include but not limited to limiting the ability to use items on animals to create a thematic of caretaking but still keeping animals "free range", but this proved unwieldy and frustrating.

**Comment by OnyxXIII** [comment]
I have a fix for the rideable issue - would you prefer this, or the inability to ride rideable mobs (while still being able to lead, feed, etc them)?

**Comment by OnyxXIII** [comment]
also, a more complete list of mobs would be nice :)

**Comment by OnyxXIII** [comment]
Nick has done, pending upload
