### ISSUE TITLE
Issue Tracker Feature Request

### ISSUE THREAD

**Issue by HalberdGuard** [OnyxXIII/New-Terrodim-Origins#25]
It would be nice to concisely and systemically express the level of urgency of a given issue or request!

I suggest adding new Labels users can apply that express a priority they feel to be appropriate to the issue they are posting, so that issues can be easily sorted accordingly! Suggest at least Low, Medium, and High; possibly also Critical, in case someone discovers something that will destroy all!

I have seen at least one other person put the priority they feel to be appropriate in the title of their issue and was tempted to do so as well; but I would argue this creates additional clutter in the title, and leaves open the possibility for more ambiguous descriptions of priority if it were to become common practice.

**Comment by OnyxXIII** [comment]
Done

**Comment by HalberdGuard** [comment]
(Can't find a way to do it.) ...Also doesn't appear to be a slash command nor available option upon creating a new issue.
