### ISSUE TITLE
Faun - Unable to Punch Reliably

### ISSUE THREAD

**Issue by HalberdGuard** [OnyxXIII/New-Terrodim-Origins#26]
When in combat, Fauns very quickly get to the point of having the "Weakness" debuff after some dodging, hitting, and being hit; this much is intentional, however as soon as "Weakness" is applied unarmed attacks no longer hit enemies.

**To Reproduce**
1. Go to the enemies.
2. Click on the enemies.
3. Be hit by the enemies.
4. Get "Weakness" debuff when feeling snacky.
5. Unarmed punches no longer hit enemies.

**Expected behavior**
I expect to be able to use punches in combat to take advantage of the unarmed knockback bonus of the Faun, and to be able to do so while under the effect of "Weakness".

**Desktop:**
 - OS: Ubuntu 22.04.3 LTS
 - Minecraft Version: 1.19.2
 - Full List of Installed Mods and Versions:
 fabric-api-0.77.0+1.19.2
 Origins-1.19.2-1.7.1
 Pehkui-3.7.12+1.14.4-1.20.4
 smallships-fabric-1.19.X-2.0.0a1.1.1
 Statement-4.2.9+1.14.4-1.20.4
 time-and-wind-ct-1.4.3+1.19.2
 Towelette-5.0.0+1.14.4-1.19.3
 
It might also be nice to slightly increase the amount of hunger-loss it takes to activate Weakness, so that the first second or two of combat are unaffected. I think the current is possibly 4 hunger lost, perhaps push it to 6 or 8; but this is tangential to the main issue.

**Comment by OnyxXIII** [comment]
This is an issue with Minecraft - Weakness, if it reduces damage to/below 0, causes the attack to be ignored entirely (thus not firing your knockback power)
 I have increased the hunger before weakness begins for this reason.
