### ISSUE TITLE
Faun - Flora Propagation Changes

### ISSUE THREAD

**Issue by HalberdGuard** [OnyxXIII/New-Terrodim-Origins#27]
**There are additional plants I would like Fauns to be able to propagate either more effectively, or at all!**

**The plants I would like to see drop items when bonemeal'd, and the item I think they should drop:**
- Tall Grass should drop Grass. (Technically decrease in efficiency for increase in convenience.)
- Large Fern should drop Small Fern. (Technically decrease in efficiency for increase in convenience.)
- Big Dripleaf should drop Small Dripleaf. (Already has a mechanic with bonemeal, but this increases efficiency and allows for collecting Small Dripleaf directly.)
- Lily Pad should drop Lily Pad. (Otherwise only renewable through fishing!)

**There are also three other plants I would like to be able to propagate, got some weird ideas here:**
- Chorus Plant should grow when a Faun uses Sugar on it! (This may or may not be possible; would settle for dropping Chorus Fruit, though that might be too easy? Maybe only works on Chorus Flowers instead, but also progresses the Flower's age, if that is possible? Also, bonemeal just didn't seem right. Sugar is maybe just weird enough to make "sense". Thoughts?)
- Right-click a Fern with Shears to turn it into a Dead Bush! (Can the "use" of Shears affect durability normally here? What if, as is common for me, the shears are enchanted with Unbreaking? I personally wouldn't mind it if it has to bypass Unbreaking for this one application, as I imagine that might be a messy thing. Alternatively, craft a Dead Bush with 3 Sticks to make 2 total Dead Bush items.)
- Spore Blossom drops Spore Blossom when Spider Eye is used on it! Yeah this is a stretch I mean it kinda' looks like a carnivorous plant almost maybe but like I can't think of anything else better that still keeps it just slightly pricey to propagate. I also tried to think of other mechanics to propagate them, but they all ended up being over-complicated or needing to create a new intermediate item.

**Comment by HalberdGuard** [comment]
Would love thoughts on any of this, but especially Spore Blossom and Dead Bush! Especially especially Spore Blossom. Still not happy with my idea.

**Comment by OnyxXIII** [comment]
So all the block-use actions are https://origins.readthedocs.io/en/1.10.0/types/power_types/action_on_block_use/
drop stuff when bone meal'd is easy (regardless of the actual item replacing bone meal)

- chorus plant: "Bonemeal" is a block action type, but chorus plants don't react to bone meal, do they? https://origins.readthedocs.io/en/1.10.0/types/block_action_types/bonemeal/
- but we can use Modify Block State to change the growth stage: https://origins.readthedocs.io/en/1.10.0/types/block_action_types/modify_block_state/
- fern; totally can change a thing when you click it with another thing. Can also damage the tool you're using with an equipped_item_action https://origins.readthedocs.io/en/1.10.0/types/item_action_types/damage/

**Comment by OnyxXIII** [comment]
Given the relative ease of all of this... I will hold off on implementing it because I think it'd be a great intro to origins dev if you wanna try your hand at it.

I have no idea on the chorus flower thing. It's definitely flavorful. A plant that vibrant surviving on cave ceilings must have some pretty good source of nutrients... spiders would be appropriate xD.

**Comment by OnyxXIII** [comment]
Done by Nick, to be uploaded
