### ISSUE TITLE
Faun - Leap Ability Consumes Hunger

### ISSUE THREAD

**Issue by HalberdGuard** [OnyxXIII/New-Terrodim-Origins#28]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when: I'm not hungry!

**Describe the solution you'd like**
I want to big jump, and then be big hungry!
(Add 1 hunger as cost to activate ability?)

**Describe alternatives you've considered**
There can be no other way.

**Additional context**
There can be no other context.

**Comment by OnyxXIII** [comment]
Done
