### ISSUE TITLE
Rotten Food Immunity Not Working- URGENT

### ISSUE THREAD

**Issue by ShampooAkatsukiFromHonk** [OnyxXIII/New-Terrodim-Origins#33]
I'm getting the hunger debuff from eating rotten flesh.

I don't know how to tag posts, but this needs to be fixed as soon as possible as I cannot play until this is fixed.

**Comment by ShampooAkatsukiFromHonk** [comment]
should specify that this is a wharfrat issue. Forgot to say that.

**Comment by OnyxXIII** [comment]
Added a 2-tick delay to the effect clear. Should work in next update. (tested)
