### ISSUE TITLE
Naga - Allow Gold Armor

### ISSUE THREAD

**Issue by GigglingMenace** [OnyxXIII/New-Terrodim-Origins#34]
### Trims Are Here

And with it, the excitement of being able to wear cool and custom armor sets.

In the past, I waffled on whether or not Nagans should be able to wear gold armor, mostly because it just didn't make sense for them to know the arts of metallurgy. Well, since the neighbors have come and taught them great things, the Dragonborn being the closest to them, and being the most curious about the Nagans, has taken liberty to teach them the art of gold metallurgy. 

Gold as an armor set is very flimsy, and I had the idea that Nagans would be more of a support role race rather than your tanky Dragonborn, or your DPS Elf on a shelf, and with the combination of "Fire Writings" from the Elves, and the art to craft something as delicate as golden plate armor just seems like the perfect testament of their growth as a race of people. (This is lore that Austin supports as well.)

That, and gold armor trimmed with amethyst just looks pretty to me. 
![Gold armor Naga](https://github.com/OnyxXIII/New-Terrodim-Origins/assets/157146589/4ec9e330-fe32-4c21-aceb-f90c429af6c1)

**Comment by OnyxXIII** [comment]
Nick has fixed - to be uploaded
