### ISSUE TITLE
*High Priority* Naga Unable to craft Coral blocks from Fans

### ISSUE THREAD

**Issue by GigglingMenace** [OnyxXIII/New-Terrodim-Origins#41]
**Describe the bug**
I can't craft Coral, as was described.

**Screenshots**
![No coral 2](https://github.com/OnyxXIII/New-Terrodim-Origins/assets/157146589/526e91b5-4555-465c-813d-0a6486589046)

**Desktop (please complete the following information about your setup):**
 - OS:  Windows 11
 - Minecraft Version: 1.20.1
 - Full List of Installed Mods and Versions:  Terrodim Mod list

**Comment by GigglingMenace** [comment]
![no coral](https://github.com/OnyxXIII/New-Terrodim-Origins/assets/157146589/7cec60bc-a7d9-449b-b29d-e8660986a722)
 
 
 The screenshot from the top messed up. This is the second one

**Comment by OnyxXIII** [comment]
Forgot to add the power to the naga power list. Should be fixed in next update.
